version: '3'

services:
  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ../backend
    ports:
      - "4000:4000"
    # depends_on:
    #   - database

  # database:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - "5432:5432"